// Helper script to add your weekly schedule
// Run this once as admin to populate your schedule

import type { ScheduleEvent, DayOfWeek } from '../types';

export const weeklyScheduleData: Omit<ScheduleEvent, 'id' | 'createdBy' | 'createdAt' | 'updatedAt'>[] = [
  // Monday
  {
    title: 'Organisation des Entreprises',
    description: 'Organisation et gestion des entreprises',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '09:00',
    endTime: '10:30',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'monday' as DayOfWeek,
  },
  {
    title: 'Algèbre',
    description: 'Cours d\'algèbre',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '10:45',
    endTime: '12:45',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'monday' as DayOfWeek,
  },
  {
    title: 'Circuit Électrique',
    description: 'Cours de circuit électrique',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '14:30',
    endTime: '16:00',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'monday' as DayOfWeek,
  },
  
  // Tuesday
  {
    title: 'Algorithme',
    description: 'Cours d\'algorithme et structures de données',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '08:30',
    endTime: '11:45',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'tuesday' as DayOfWeek,
  },
  {
    title: 'Comptabilité',
    description: 'Cours de comptabilité',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '12:30',
    endTime: '14:00',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'tuesday' as DayOfWeek,
  },
  
  // Wednesday
  {
    title: 'Analyse de Controverses',
    description: 'Analyse de controverses',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '09:00',
    endTime: '10:30',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'wednesday' as DayOfWeek,
  },
  {
    title: 'MTU',
    description: 'Mathématiques et Techniques de l\'Univers',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '10:45',
    endTime: '12:45',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'wednesday' as DayOfWeek,
  },
  {
    title: 'Langage de Programmation',
    description: 'Cours de langage de programmation',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '14:00',
    endTime: '17:15',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'wednesday' as DayOfWeek,
  },
  
  // Thursday
  {
    title: 'Analyse',
    description: 'Cours d\'analyse mathématique',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '08:30',
    endTime: '10:30',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'thursday' as DayOfWeek,
  },
  {
    title: 'Circuit Numérique',
    description: 'Cours de circuit numérique',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '10:45',
    endTime: '12:15',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'thursday' as DayOfWeek,
  },
  {
    title: 'TP Circuit Électrique',
    description: 'Travaux pratiques de circuit électrique',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '14:00',
    endTime: '16:00',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'thursday' as DayOfWeek,
  },
  {
    title: 'TP Langage de Programmation',
    description: 'Travaux pratiques de programmation',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '16:15',
    endTime: '18:15',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'thursday' as DayOfWeek,
  },
  
  // Friday
  {
    title: 'English',
    description: 'English language course',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '09:00',
    endTime: '10:30',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'friday' as DayOfWeek,
  },
  {
    title: 'Français',
    description: 'Cours de français',
    type: 'class',
    startDate: '2024-01-01',
    endDate: '2099-12-31',
    startTime: '10:45',
    endTime: '12:15',
    location: '',
    subjectId: undefined,
    isRecurring: true,
    dayOfWeek: 'friday' as DayOfWeek,
  },
];

